#!/bin/bash

# yum install nmap-ncat

# Chosen to be a bit bigger than journald's configured SystemMaxSize, 1.1 GBs
# or 1,100 MBs.
TOTAL_SIZE=1100
# Should give us 110 data points during the run no matter what the message size
# is used below, 10 MBs.
REPORT_SIZE=10

NCFIFO="/tmp/nc-rsyslog-514"


function get_invocid {
    # FIXME this prefix, "testload01" is currently in an rsyslog rulebase to
    # make this work with a particular rsyslog config.
    echo "testload01_${1}"
}

function run_loader_journal_via_syslog_w_verify() {
    msgsize=${1}
    echo    loader --invocid="$(get_invocid ${msgsize})" --stddev=1 --distribution=normal --payload-gen=random --total-size=$TOTAL_SIZE --report-interval=$REPORT_SIZE --output=syslog ${msgsize}

    # Setup nc listener piping to a named pipe
    rm -f $NCFIFO
    mkfifo $NCFIFO
    nc -k -l localhost 514 --recv-only > $NCFIFO 2> /dev/null < /dev/null &
    ncpid=$!
    sleep 1

    # Setup the verify to read from that named pipe to process its data
    ../verify-loader --report-interval=$REPORT_SIZE --emit-loader-stats < $NCFIFO &
    verpid=$!
    sleep 1
    
    # Setup rsyslog running
    /usr/sbin/rsyslogd -n -f /etc/rsyslog.conf > /dev/null 2>&1 < /dev/null &
    rsyslogpid=$!
    sleep 1

    # Be sure we shutdown the above setup on Ctrl-C
    trap "kill -TERM $rsyslogpid 2>/dev/null; kill -TERM $ncpid 2>/dev/null; kill -TERM $verpid 2>/dev/null; rm -f $NCFIFO" INT

    # Give the above setup 10 seconds to settle down
    sleep 10

    # Run the loader until completion
         ../loader --invocid="$(get_invocid ${msgsize})" --stddev=1 --distribution=normal --payload-gen=random --total-size=$TOTAL_SIZE --report-interval=$REPORT_SIZE --output=syslog ${msgsize}

    # Give the SUT 10 seconds to settle down
    sleep 10

    # Stop the infrastructure
    kill -TERM $rsyslogpid 2>/dev/null
    kill -TERM $ncpid 2>/dev/null
    kill -TERM $verpid 2>/dev/null
 
    # Wait for the verifier to terminate before doing anything else
    wait $verpid 2>/dev/null

    # Wait for the others in reverse order
    wait $ncpid 2>/dev/null
    wait $rsyslogpid 2>/dev/null
    rm -f $NCFIFO
    trap - INT
}

run_loader_journal_via_syslog_w_verify ${1}
